export { default as TableComponent } from './Table'
export { default as TableHeader } from './TableHead'
export { default as TableFooter } from './TableFooter'
export { default as TableBody } from './TableBody'
export { default as TableRow } from './TableRow'
