export { default as Error } from './Error'
export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Sales } from './Sales'
export { default as Settings } from './Settings'
