//mock data
export type ProductType = typeof productSample
const productSample = {
  Class: '',
  CreatedBy: 'fg',
  CreatedOn: '2024-02-14T11:03:02.000Z',
  DelFlag: 0,
  FKCmpID: 0,
  FKGroupID: 0,
  FKManufactureID: 18,
  FKStoreID: 0,
  FKUnitID: 0,
  HSNCode: 'HSN0001',
  ItemCode: 'IT0001',
  ItemName: 'Icecream',
  Lcost: 0,
  MaxLevel: 0,
  ModifiedBy: 0,
  ModifiedOn: '2024-03-04T16:00:28.000Z',
  PKItemID: 13,
  Price: 30,
  Qty: 75,
  ReOrderLevel: 0,
  RepFlag: 0,
  TaxPer: 0,
  qty: 1,
}

// export const products = [
//   {
//     id: 1,
//     name: 'Milk',
//     imageSrc: 'milk.jpeg',
//     price: 2.5,
//     qty: 1,
//   },
//   {
//     id: 2,
//     name: 'Apple',
//     imageSrc: 'apple.jpg',
//     price: 1.0,
//     qty: 1,
//   },
//   {
//     id: 3,
//     name: 'Banana',
//     imageSrc: 'banana.jpg',
//     price: 0.5,
//     qty: 1,
//   },
//   {
//     id: 4,
//     name: 'Orange',
//     imageSrc: 'orange.jpg',
//     price: 0.75,
//     qty: 1,
//   },
//   {
//     id: 5,
//     name: 'Rice',
//     imageSrc: 'rice.jpg',
//     price: 3.0,
//     qty: 1,
//   },
//   {
//     id: 6,
//     name: 'Strawberry',
//     imageSrc: 'strawberry.jpg',
//     price: 2.0,
//     qty: 1,
//   },
//   {
//     id: 7,
//     name: 'Lettuce',
//     imageSrc: 'lettuce.jpg',
//     price: 1.5,
//     qty: 1,
//   },
//   {
//     id: 8,
//     name: 'Tomato',
//     imageSrc: 'tomato.jpg',
//     price: 1.25,
//     qty: 1,
//   },
//   {
//     id: 9,
//     name: 'Bread',
//     imageSrc: 'bread.jpg',
//     price: 2.75,
//     qty: 1,
//   },
//   {
//     id: 10,
//     name: 'Eggs',
//     imageSrc: 'eggs.jpg',
//     price: 2.0,
//     qty: 1,
//   },
//   {
//     id: 11,
//     name: 'Potato',
//     imageSrc: 'potato.jpg',
//     price: 1.2,
//     qty: 1,
//   },
//   {
//     id: 12,
//     name: 'Onion',
//     imageSrc: 'onion.jpg',
//     price: 0.8,
//     qty: 1,
//   },
// ]
